import logging
import os
import sys

# Ensure logs directory exists
LOG_DIR = "logs"
os.makedirs(LOG_DIR, exist_ok=True)

# Create logger
logger = logging.getLogger("datachat")
logger.setLevel(logging.INFO)

# Prevent duplicate handlers if re-imported
if not logger.handlers:
    # Formatter
    formatter = logging.Formatter(
        fmt="%(asctime)s - %(levelname)s - %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S"
    )

    # File handler
    file_handler = logging.FileHandler(os.path.join(LOG_DIR, "datachat.log"))
    file_handler.setFormatter(formatter)

    # Console handler
    console_handler = logging.StreamHandler()
    console_handler.stream = open(sys.stdout.fileno(), 
        mode='w', 
        encoding='utf-8', 
        buffering=1)
    console_handler.setFormatter(formatter)

    # Add handlers
    logger.addHandler(file_handler)
    #logger.addHandler(console_handler)


def log_question(question: str):
    """
    Logs the user's natural language question for audit and debugging.
    
    Args:
        question (str): The user's natural language question.
    """
    logger.info(f"Question: {question}")


def log_sql(sql: str):
    """
    Logs the generated SQL query for audit and debugging.
    
    Useful for understanding what SQL was generated from a user question
    and for debugging Claude's interpretation of user intent.
    
    Args:
        sql (str): The SQL query generated by Claude.
    """
    logger.info(f"SQL: {sql}")


def log_execution_time(operation: str, seconds: float):
    """
    Logs the execution time of an operation with microsecond precision.
    
    Helps identify performance bottlenecks. Times are logged with 4 decimal
    places for granular performance tracking.
    
    Args:
        operation (str): Name of the operation being timed.
        seconds (float): Execution time in seconds.
    """
    logger.info(f"{operation} took {seconds:.4f} seconds")


def log_error(error: str):
    """
    Logs an error message with ERROR level severity.
    
    Ensures errors are prominently logged and can be filtered in log aggregation
    systems that parse log levels.
    
    Args:
        error (str): The error message to log.
    """
    logger.error(f"Error: {error}")


def log_result_count(count: int):
    """
    Logs the number of rows returned from a query.
    
    Helps track query result sizes for monitoring and understanding data
    retrieval patterns.
    
    Args:
        count (int): The number of rows returned.
    """
    logger.info(f"Rows returned: {count}")