import re
from config import DANGEROUS_INPUT_KEYWORDS, DANGEROUS_SQL_KEYWORDS

def is_input_safe(user_input: str) -> bool:
    """
    Validates user input for dangerous SQL keywords that could indicate attacks.
    
    Checks if the user's natural language question contains suspicious keywords
    like DROP, DELETE, UPDATE, etc. This is a first line of defense against prompt
    injection and malicious queries, catching obvious attempts.
    
    Args:
        user_input (str): The user's natural language question.
        
    Returns:
        bool: True if input is safe, False if dangerous keywords detected.
    """
    upper_input = user_input.upper()
    return not any(keyword in upper_input for keyword in DANGEROUS_INPUT_KEYWORDS)


def is_sql_safe(sql: str) -> bool:
    """
    Validates generated SQL for dangerous keywords before execution.
    
    Final safety check to ensure Claude-generated SQL doesn't contain destructive
    operations like DELETE or UPDATE, even if the request seemed safe. This blocks
    execution of any SQL with dangerous keywords regardless of source.
    
    Args:
        sql (str): The SQL query generated by Claude.
        
    Returns:
        bool: True if SQL is safe to execute, False if dangerous keywords detected.
    """
    upper_sql = sql.upper()
    return not any(keyword in upper_sql for keyword in DANGEROUS_SQL_KEYWORDS)


def extract_sql(raw_response: str) -> str:
    """
    Extracts clean SQL from Claude's response by removing markdown formatting.
    
    Claude often wraps SQL in markdown code blocks (```sql ... ```). This function
    removes those formatting markers and whitespace to get the raw SQL string for
    execution. Handles both labeled (```sql) and unlabeled (```) code blocks.
    
    Args:
        raw_response (str): The raw text response from Claude.
        
    Returns:
        str: The extracted SQL query without markdown formatting.
    """
    # Remove ```sql ... ``` or ``` ... ``` markdown code blocks
    cleaned = re.sub(r"```sql\s*([\s\S]*?)```", r"\1", raw_response, flags=re.IGNORECASE)
    cleaned = re.sub(r"```\s*([\s\S]*?)```", r"\1", cleaned)

    # Strip leading/trailing whitespace
    return cleaned.strip()


if __name__ == "__main__":
    # Test cases
    tests = []

    # Test is_input_safe
    tests.append(("Input Safe", is_input_safe("Show all users") == True))
    tests.append(("Input Unsafe", is_input_safe("DROP TABLE users") == False))

    # Test is_sql_safe
    tests.append(("SQL Safe", is_sql_safe("SELECT * FROM users") == True))
    tests.append(("SQL Unsafe", is_sql_safe("DELETE FROM users") == False))

    # Test extract_sql
    raw = "```sql\nSELECT * FROM users;\n```"
    extracted = extract_sql(raw)
    tests.append(("Extract SQL", extracted == "SELECT * FROM users;"))

    # Print results
    for name, result in tests:
        print(f"{name}: {'PASS' if result else 'FAIL'}")